--접속유저의 모든 테이블 삭제
BEGIN
    FOR C IN (SELECT TABLE_NAME FROM USER_TABLES) LOOP
    EXECUTE IMMEDIATE ('DROP TABLE '||C.TABLE_NAME||' CASCADE CONSTRAINTS');
    END LOOP;
END;
/

--접속유저의 모든 시퀀스 삭제
BEGIN
FOR C IN (SELECT * FROM USER_SEQUENCES) LOOP
  EXECUTE IMMEDIATE 'DROP SEQUENCE '||C.SEQUENCE_NAME;
END LOOP;
END;
/

--접속유저의 모든 뷰 삭제
BEGIN
FOR C IN (SELECT * FROM USER_VIEWS) LOOP
  EXECUTE IMMEDIATE 'DROP VIEW '||C.VIEW_NAME;
END LOOP;
END;
/
-----------테이블----------
-- MEMBER(유저/회원)테이블
CREATE TABLE MEMBER(
    MEM_NO NUMBER PRIMARY KEY,
    MEM_EMAIL VARCHAR2(60) UNIQUE,
    MEM_PWD VARCHAR2(60) NULL,
    MEM_NAME VARCHAR2(60) NOT NULL,
    MEM_CONCERN VARCHAR2(30),
    MEM_PRO NUMBER DEFAULT 1 NOT NULL,
    PHONE VARCHAR2(30) NOT NULL,
    LOCATION VARCHAR2(100),
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    MEM_GEN VARCHAR2(10) NOT NULL CHECK(MEM_GEN IN ('M','F')), 
    POINT NUMBER,
    FILE_PATH VARCHAR2(3000) DEFAULT 'resources/memberProfileImg/userDefaultProFile.png',
    ACCOUNT NUMBER DEFAULT 0,
    INTRO VARCHAR2(3000),
    ENROLL_DATE DATE DEFAULT SYSDATE
);

--멤버 시퀀스
CREATE SEQUENCE SEQ_MNO
START WITH 2
INCREMENT BY 1
MAXVALUE 99
NOCYCLE
NOCACHE;

----SORT(분류(카테고리상세))테이블
--CREATE TABLE SORT(
--    SORT_NO NUMBER PRIMARY KEY,
--    SORT_NAME VARCHAR2(300) NOT NULL
--);
--
----SORT 시퀀스
--CREATE SEQUENCE SEQ_SNO
--START WITH 100
--INCREMENT BY 1
--MAXVALUE 199
--NOCYCLE
--NOCACHE;

--CATEGORY(카테고리)테이블
CREATE TABLE CATEGORY(
    CATEGORY_NO NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(200) NOT NULL
);

--CATEGORY 시퀀스
CREATE SEQUENCE SEQ_CNO
START WITH 200
INCREMENT BY 1
MAXVALUE 299
NOCYCLE
NOCACHE;

CREATE TABLE PROFESSIONAL(
    PRO_NO NUMBER PRIMARY KEY,
    PRO_JOB VARCHAR2(60),
    CATEGORY_NO NUMBER REFERENCES CATEGORY(CATEGORY_NO),
    MEM_NO NUMBER REFERENCES MEMBER(MEM_NO)
);

--PRO 시퀀스
CREATE SEQUENCE SEQ_PNO
START WITH 300
INCREMENT BY 1
MAXVALUE 999
NOCYCLE
NOCACHE;

-- BOARD(게시판)테이블
CREATE TABLE BOARD(
  BOARD_NO NUMBER PRIMARY KEY,
  BOARD_TITLE VARCHAR2(60) NOT NULL,
  BOARD_CONTENT VARCHAR2(3000) NOT NULL,
  PRICE NUMBER,
  BOARD_TYPE NUMBER CHECK(BOARD_TYPE IN(1, 2, 3, 4, 5)),
  CREATEDATE DATE DEFAULT SYSDATE NOT NULL,
  STATUS VARCHAR2(3) DEFAULT 'Y',
  MEM_NO NUMBER REFERENCES MEMBER(MEM_NO),
  CATEGORY_NO NUMBER REFERENCES CATEGORY(CATEGORY_NO),
  LIKEY_COUNT NUMBER DEFAULT 0,
  VIEW_COUNT NUMBER DEFAULT 0
);

--BOARD 시퀀스
CREATE SEQUENCE SEQ_BNO
START WITH 1000
INCREMENT BY 1
MAXVALUE 9999
NOCYCLE
NOCACHE;

--REPLY 테이블 생성
CREATE TABLE REPLY(
    REPLY_NO NUMBER PRIMARY KEY,
    REPLY_CONTENT VARCHAR2(3000) NOT NULL,
    CREATEDATE DATE DEFAULT SYSDATE NOT NULL,
    MEM_NO NUMBER REFERENCES MEMBER(MEM_NO),
    BOARD_NO NUMBER REFERENCES BOARD(BOARD_NO),
    STATUS VARCHAR2(3) DEFAULT 'Y',
    RELIKEY_COUNT NUMBER DEFAULT 0
);

-- REPLY 시퀀스
CREATE SEQUENCE SEQ_RNO
START WITH 20001
INCREMENT BY 1
MAXVALUE 25000
NOCYCLE
NOCACHE;

--ATTACHMENT테이블
CREATE TABLE ATTACHMENT(
    ATT_NO NUMBER PRIMARY KEY,
    ORIGIN_NAME VARCHAR2(2000) NOT NULL,
    CHANGE_NAME VARCHAR2(2000) NOT NULL,
    FILE_PATH VARCHAR2(3000),
    STATUS VARCHAR2(3) DEFAULT 'Y',
    BOARD_NO NUMBER REFERENCES BOARD(BOARD_NO)
);

--ATTACHMENT 시퀀스
CREATE SEQUENCE SEQ_ANO
START WITH 10000
INCREMENT BY 1
MAXVALUE 15000
NOCYCLE
NOCACHE;

--NOTICE 공지사항 테이블
CREATE TABLE NOTICE(
    NOTICE_NO NUMBER PRIMARY KEY,
    NOTICE_TYPE VARCHAR2(30) DEFAULT '공지' NOT NULL,
    NOTICE_TITLE VARCHAR2(2000) NOT NULL,
    NOTICE_CONTENT VARCHAR2(2000) NOT NULL,
    CREATEDATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS VARCHAR2(3) DEFAULT 'Y' NOT NULL
);

--NOTICE 시퀀스
CREATE SEQUENCE SEQ_NNO
START WITH 15001
INCREMENT BY 1
MAXVALUE 20000
NOCYCLE
NOCACHE;

--SCHEDULE(요청) 테이블
CREATE TABLE SCHEDULE(
    SCHE_NO NUMBER PRIMARY KEY,
    SCHE_TITLE VARCHAR2(2000) NOT NULL,
    SCHE_CONTENT VARCHAR2(2000) NOT NULL,
    BOARD_NO NUMBER REFERENCES BOARD(BOARD_NO),
    FROM_MNO NUMBER REFERENCES MEMBER(MEM_NO),
    TO_MNO NUMBER REFERENCES MEMBER(MEM_NO),
    CATEGORY_NO NUMBER REFERENCES CATEGORY(CATEGORY_NO),
    STATUS VARCHAR2(3) DEFAULT 'Y' NOT NULL,
    CREATEDATE DATE DEFAULT SYSDATE NOT NULL,
    LOCATION VARCHAR2(2000) NOT NULL
);

-- SCHEDULE(요청)시퀀스
CREATE SEQUENCE SEQ_SNO START WITH 100000 INCREMENT BY 1 MAXVALUE 109999 NOCYCLE NOCACHE;

-- AUTHENTICATE(이메일인증 난수)테이블
CREATE TABLE AUTHENTICATE(
    AUTH_NO NUMBER PRIMARY KEY,
    AUTH_EMAIL VARCHAR2(1000) NOT NULL,
    AUTH_RANDOM NUMBER NOT NULL,
    CREATEDATE DATE DEFAULT SYSDATE NOT NULL
);

-- AUTHENTICATE 시퀀스
CREATE SEQUENCE SEQ_AUNO
START WITH 1000000
INCREMENT BY 1
MAXVALUE 1050000
NOCYCLE
NOCACHE;


--채팅방 테이블 생성
CREATE TABLE CHATROOM(
    CHAT_ROOM_NO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL, 
    STATUS CHAR(1) NOT NULL,
    MEM_NO NUMBER REFERENCES MEMBER(MEM_NO)
);

--채팅방 시퀀스
CREATE SEQUENCE SEQ_CRNO
START WITH 1
INCREMENT BY 1
MAXVALUE 9999
NOCYCLE
NOCACHE;

--메시지 테이블 생성
CREATE TABLE CHATMSG(
    MSG_NO NUMBER PRIMARY KEY,
    MSG VARCHAR2(4000) NOT NULL,
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CHAT_ROOM_NO NUMBER REFERENCES CHATROOM(CHAT_ROOM_NO),
    MEM_NO NUMBER REFERENCES MEMBER(MEM_NO)
);

--메시지 시퀀스
CREATE SEQUENCE SEQ_MSGNO
START WITH 1
INCREMENT BY 1
MAXVALUE 9999
NOCYCLE
NOCACHE;

CREATE TABLE CHATROOMJOIN(
    MEM_NO NUMBER REFERENCES MEMBER(MEM_NO),
    CHAT_ROOM_NO NUMBER REFERENCES CHATROOM(CHAT_ROOM_NO)
);

CREATE TABLE LIKEY(
LIKEY_NO NUMBER PRIMARY KEY,
BOARD_NO NUMBER NOT NULL,
MEM_NO NUMBER NOT NULL,
LISTATUS VARCHAR2(2) DEFAULT 'N'
);

-- 좋아요 시퀀스
CREATE SEQUENCE SEQ_LNO
START WITH 300000
INCREMENT BY 1
MAXVALUE 400000
NOCYCLE
NOCACHE;

CREATE TABLE REPLY_LIKEY(
RELIKEY_NO NUMBER PRIMARY KEY,
REPLY_NO NUMBER NOT NULL,
BOARD_NO NUMBER NOT NULL,
MEM_NO NUMBER NOT NULL,
RE_LISTATUS VARCHAR2(2) DEFAULT 'N'
);

-- 좋아요 시퀀스
CREATE SEQUENCE SEQ_RLNO
START WITH 400001
INCREMENT BY 1
MAXVALUE 500000
NOCYCLE
NOCACHE;

--PAY테이블생성
CREATE TABLE PAY (
    PAY_NO NUMBER PRIMARY KEY,
    PRICE NUMBER NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    MEM_NO NUMBER REFERENCES MEMBER(MEM_NO)
);

--PAY 시퀀스
CREATE SEQUENCE SEQ_PAY_NO
START WITH 700000
INCREMENT BY 1
MAXVALUE 710000
NOCYCLE
NOCACHE;

--REASON테이블 탈퇴사유
CREATE TABLE REASON (
    MEM_NO NUMBER REFERENCES MEMBER (MEM_NO) UNIQUE,
    REA_CONTENT VARCHAR2(3000) NOT NULL,
    RETIRE_DATE DATE DEFAULT SYSDATE
);
---------------------더미데이터-----------------------
-- 멤버
INSERT INTO MEMBER VALUES(1, 'admin@naver.com', '$2a$10$Oa0Xd4NXm4.5/lgBkeBbBu2Y3gHAkhdOT9zgvilBHgO0dBYu1dNCm' ,'관리자', '음악', 1,
        '010-1111-0000', '서울시 강남구', 'Y', 'M', '4', 'resources/memberProfileImg/userDefaultProFile.png', 0, NULL, SYSDATE);
INSERT INTO MEMBER VALUES(SEQ_MNO.NEXTVAL, 'user01@naver.com','$2a$10$Oa0Xd4NXm4.5/lgBkeBbBu2Y3gHAkhdOT9zgvilBHgO0dBYu1dNCm' ,'홍길동', '음악', 1, 
        '010-1111-1111', '서울시 송파구', 'Y', 'M', '4', 'resources/memberProfileImg/userDefaultProFile.png', 0, NULL, SYSDATE);

INSERT INTO MEMBER(
            MEM_NO,
			MEM_EMAIL,
			MEM_PWD,
			MEM_NAME,
			MEM_CONCERN,
			PHONE,
			MEM_GEN,
            INTRO,
            ENROLL_DATE
		)
		VALUES(
            SEQ_MNO.NEXTVAL,
			'aaa@naver.com',
			'1111',
			'김개똥',
			'요리',
			'010-2222-2222',
			'M',
            NULL,
            SYSDATE
		);
--카테고리
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '음악');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '운동');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '게임');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '미술');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '댄스');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '요리');
---- 카테고리 수정안 추가본
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '교육');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '취미');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '뷰티');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '패션');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '건강');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '펫');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '부동산');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '자동차');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '금융');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, 'IT');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '기타');
--프로
INSERT INTO PROFESSIONAL VALUES(SEQ_PNO.NEXTVAL, '피아니스트', 200, 2);

--게시판(보드)
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '음악레슨합니다', '음악 정말 즐겁게 알려드려요', 50000, 1, '2020-01-01', 'Y', 2, 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '음악레슨합니다', '음악 정말 즐겁게 알려드려요', 50000, 1, '2020-02-01', 'Y', 2, 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '음악레슨합니다', '음악 정말 즐겁게 알려드려요', 50000, 1, '2020-03-01', 'Y', 2, 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '음악레슨합니다', '음악 정말 즐겁게 알려드려요', 50000, 1, '2020-04-01', 'Y', 2, 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '도와주세요', '피아노 알려주세요', 50000, 2, '2020-01-30', 'Y', 2, 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '운동도와주세요', '테니스 알려주세요', 50000, 2, '2020-02-20', 'Y', 2, 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '커뮤니티용 음악레슨합니다1', '커뮤니티용 음악 정말 즐겁게 알려드려요', 50000, 3, '2020-01-02', 'Y', 2, 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '얼마예요1', '커뮤니티용 음악 정말 즐겁게 알려드려요', 40000, 4, '2020-01-03', 'Y', 2, 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '함께해요1', '커뮤니티용 음악 정말 즐겁게 알려드려요', 40000, 5, '2020-01-04', 'Y', 2, 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '궁금해요2', '커뮤니티용 음악 정말 즐겁게 알려드려요', 40000, 3, '2020-01-05', 'Y', 2, 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '얼마예요2', '커뮤니티용 음악 정말 즐겁게 알려드려요', 40000, 4, '2020-01-06', 'Y', 2, 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '함께2', '커뮤니티용 음악 정말 즐겁게 알려드려요', 40000, 5, '2020-01-07', 'Y', 2, 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '커뮤니티용 페이징처리', '커뮤니티용 음악 정말 즐겁게 알려드려요', 40000, 3, '2020-01-08', 'Y', 2, 200, 0, 0);
-- ATTACHEMT 사진
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '33', '4' , 'Y' ,1000);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '33', '4' , 'Y' ,1001);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '33', '4' , 'Y' ,1002);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '33', '4' , 'Y' ,1003);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '33', '4' , 'Y' ,1004);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '33', '4' , 'Y' ,1005);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '33', '4' , 'Y' ,1006);
-- NOTICE
INSERT INTO NOTICE VALUES(SEQ_NNO.NEXTVAL, '필독', '품앗이에 대하여', '품앗이 사이트는 전문가 및 준전문가와 수요자의 매칭을 해주는 사이트입니다.', '2020-01-01', 'Y');
INSERT INTO NOTICE VALUES(SEQ_NNO.NEXTVAL, '필독', '품앗이 채용 사칭 스미싱 문자 주의', '다른 번호 외에 전화를 걸지 말아 주시고,
소비자 보호를 위해 스미싱 사이트에 접속하지 말아주시길 당부 드립니다.', '2020-01-01', 'Y');
INSERT INTO NOTICE VALUES(SEQ_NNO.NEXTVAL, '공지', '품앗이 서비스 점검안내', '사이트 및 서버 점검이 진행 될 예정입니다.
점검시간 동안 품앗이 사이트 서비스 이용이 불가능하오니 양해 부탁드립니다.', '2020-01-01', 'Y');
INSERT INTO NOTICE VALUES(SEQ_NNO.NEXTVAL, '공지', '품앗이 사기 당했을 경우', '사기 당했을 경우 신고바랍니다.', '2020-01-01', 'Y');
INSERT INTO NOTICE VALUES(SEQ_NNO.NEXTVAL, '공지', '품앗이 현피뜰 경우', '금일은 서비스 점검으로 인해 오후에 사용이 어려울 수 있습니다.
고객놈들께서는 참고하시고 이용을 하든지 말든지 진짜 귀찮게 굴지 마시고
알아서 하시길...', SYSDATE, 'Y');
INSERT INTO NOTICE VALUES(SEQ_NNO.NEXTVAL, '공지', '품앗이생활은 감옥생활', '품앗이 생활 한번 시작하면은 못빠져나간다', SYSDATE, 'Y');
-- SCHEDULE
INSERT INTO SCHEDULE VALUES(SEQ_SNO.NEXTVAL, '음악레슨신청1', '아무것도모르는 초보입니다 그래도 배워보고싶습니다1', 1000, 1, 2, 200, 'Y', SYSDATE, '서울시 강남구 역삼동');
INSERT INTO SCHEDULE VALUES(SEQ_SNO.NEXTVAL, '음악레슨신청2', '아무것도모르는 초보입니다 그래도 배워보고싶습니다2', 1000, 1, 2, 200, 'Y', SYSDATE, '서울시 강남구 역삼동');
INSERT INTO SCHEDULE VALUES(SEQ_SNO.NEXTVAL, '음악레슨신청3', '아무것도모르는 초보입니다 그래도 배워보고싶습니다3', 1000, 1, 2, 200, 'Y', SYSDATE, '서울시 강남구 역삼동');
INSERT INTO SCHEDULE VALUES(SEQ_SNO.NEXTVAL, '음악레슨신청4', '아무것도모르는 초보입니다 그래도 배워보고싶습니다4', 1000, 1, 2, 200, 'Y', SYSDATE, '서울시 강남구 역삼동');


INSERT INTO REPLY (
					REPLY_NO,
					REPLY_CONTENT,			
					MEM_NO,
					BOARD_NO,
					CREATEDATE,
					STATUS		
            		)
		VALUES(
		        SEQ_RNO.NEXTVAL,
		        '진짜 뭐하는 거임?',
		        1,
                1001,
		        SYSDATE,
		        'Y'
		        );


		SELECT  R.REPLY_NO,
				R.REPLY_CONTENT,
				M.MEM_NAME,
				R.CREATEDATE        		        
		FROM	REPLY R	
		JOIN MEMBER M ON (R.MEM_NO = M.MEM_NO) 
		WHERE R.STATUS = 'Y'
			AND BOARD_NO = 1013
		ORDER BY REPLY_NO DESC;
        

--채팅방 더미
INSERT INTO CHATROOM VALUES(5555, '제목TEST Y', 'Y', 2);
INSERT INTO CHATROOM VALUES(5556, '제목TEST N', 'N', 2);
--메시지 더미
INSERT INTO CHATMSG VALUES(5555, '메시지TEST', SYSTIMESTAMP, 5555, 2);
--채팅룸x멤버 복합키 더미
INSERT INTO CHATROOMJOIN VALUES(2, 5555);

---트랜잭션
commit;


--게시판 좋아요 트리거
CREATE OR REPLACE TRIGGER likey_status_trigger
AFTER UPDATE ON LIKEY
FOR EACH ROW
WHEN (OLD.LISTATUS <> NEW.LISTATUS)
DECLARE
    likey_increment INTEGER;
BEGIN
    IF :NEW.LISTATUS = 'Y' THEN
        likey_increment := 1;
    ELSE
        likey_increment := -1;
    END IF;

    UPDATE BOARD
    SET LIKEY_COUNT = LIKEY_COUNT + likey_increment
    WHERE BOARD_NO = :NEW.BOARD_NO;
END;
/


--게시판 댓글 좋아요 트리거
CREATE OR REPLACE TRIGGER relikey_status_trigger
AFTER UPDATE ON REPLY_LIKEY
FOR EACH ROW
WHEN (OLD.RE_LISTATUS <> NEW.RE_LISTATUS)
DECLARE
    relikey_increment INTEGER;
BEGIN
    IF :NEW.RE_LISTATUS = 'Y' THEN
        relikey_increment := 1;
    ELSE
        relikey_increment := -1;
    END IF;

    UPDATE REPLY
    SET RELIKEY_COUNT = RELIKEY_COUNT + relikey_increment
    WHERE REPLY_NO = :NEW.REPLY_NO;
END;
/