--접속유저의 모든 테이블 삭제
BEGIN
    FOR C IN (SELECT TABLE_NAME FROM USER_TABLES) LOOP
    EXECUTE IMMEDIATE ('DROP TABLE '||C.TABLE_NAME||' CASCADE CONSTRAINTS');
    END LOOP;
END;
/

--접속유저의 모든 시퀀스 삭제
BEGIN
FOR C IN (SELECT * FROM USER_SEQUENCES) LOOP
  EXECUTE IMMEDIATE 'DROP SEQUENCE '||C.SEQUENCE_NAME;
END LOOP;
END;
/

--접속유저의 모든 뷰 삭제
BEGIN
FOR C IN (SELECT * FROM USER_VIEWS) LOOP
  EXECUTE IMMEDIATE 'DROP VIEW '||C.VIEW_NAME;
END LOOP;
END;
/
-----------테이블----------
-- MEMBER(유저/회원)테이블
CREATE TABLE MEMBER(
    MEM_NO NUMBER PRIMARY KEY,
    MEM_EMAIL VARCHAR2(60) NOT NULL UNIQUE,
    MEM_PWD VARCHAR2(60) NOT NULL,
    MEM_NAME VARCHAR2(60) NOT NULL,
    MEM_CONCERN VARCHAR2(30),
    MEM_PRO NUMBER DEFAULT 1 NOT NULL,
    PHONE VARCHAR2(30) NOT NULL,
    LOCATION VARCHAR2(100),
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    MEM_GEN VARCHAR2(10) NOT NULL CHECK(MEM_GEN IN ('M','F')), 
    POINT NUMBER,
    FILE_PATH VARCHAR2(3000) DEFAULT 'resources/memberProfileImg/userDefaultProFile.png',
    ACCOUNT NUMBER DEFAULT 0,
    INTRO VARCHAR2(3000)
);

--멤버 시퀀스
CREATE SEQUENCE SEQ_MNO
START WITH 2
INCREMENT BY 1
MAXVALUE 99
NOCYCLE
NOCACHE;

----SORT(분류(카테고리상세))테이블
--CREATE TABLE SORT(
--    SORT_NO NUMBER PRIMARY KEY,
--    SORT_NAME VARCHAR2(300) NOT NULL
--);
--
----SORT 시퀀스
--CREATE SEQUENCE SEQ_SNO
--START WITH 100
--INCREMENT BY 1
--MAXVALUE 199
--NOCYCLE
--NOCACHE;

--CATEGORY(카테고리)테이블
CREATE TABLE CATEGORY(
    CATEGORY_NO NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(200) NOT NULL
);

--CATEGORY 시퀀스
CREATE SEQUENCE SEQ_CNO
START WITH 200
INCREMENT BY 1
MAXVALUE 299
NOCYCLE
NOCACHE;

CREATE TABLE PROFESSIONAL(
    PRO_NO NUMBER PRIMARY KEY,
    PRO_JOB VARCHAR2(60),
    CATEGORY_NO NUMBER REFERENCES CATEGORY(CATEGORY_NO),
    MEM_NO NUMBER REFERENCES MEMBER(MEM_NO)
);

--PRO 시퀀스
CREATE SEQUENCE SEQ_PNO
START WITH 300
INCREMENT BY 1
MAXVALUE 999
NOCYCLE
NOCACHE;

-- BOARD(게시판)테이블
CREATE TABLE BOARD(
  BOARD_NO NUMBER PRIMARY KEY,
  BOARD_TITLE VARCHAR2(60) NOT NULL,
  BOARD_CONTENT VARCHAR2(3000) NOT NULL,
  PRICE NUMBER,
  BOARD_TYPE NUMBER CHECK(BOARD_TYPE IN(1, 2, 3, 4, 5)),
  CREATEDATE DATE DEFAULT SYSDATE NOT NULL,
  STATUS VARCHAR2(3) DEFAULT 'Y',
  MEM_NO NUMBER REFERENCES MEMBER(MEM_NO),
  CATEGORY_NO NUMBER REFERENCES CATEGORY(CATEGORY_NO)
);

--BOARD 시퀀스
CREATE SEQUENCE SEQ_BNO
START WITH 1000
INCREMENT BY 1
MAXVALUE 9999
NOCYCLE
NOCACHE;

--ATTACHMENT테이블
CREATE TABLE ATTACHMENT(
    ATT_NO NUMBER PRIMARY KEY,
    ORIGIN_NAME VARCHAR2(2000) NOT NULL,
    CHANGE_NAME VARCHAR2(2000) NOT NULL,
    FILE_PATH VARCHAR2(3000),
    STATUS VARCHAR2(3) DEFAULT 'Y',
    BOARD_NO NUMBER REFERENCES BOARD(BOARD_NO)
);

--ATTACHMENT 시퀀스
CREATE SEQUENCE SEQ_ANO
START WITH 10000
INCREMENT BY 1
MAXVALUE 15000
NOCYCLE
NOCACHE;

--NOTICE 공지사항 테이블
CREATE TABLE NOTICE(
    NOTICE_NO NUMBER PRIMARY KEY,
    NOTICE_TYPE VARCHAR2(30) DEFAULT '공지' NOT NULL,
    NOTICE_TITLE VARCHAR2(2000) NOT NULL,
    NOTICE_CONTENT VARCHAR2(2000) NOT NULL,
    CREATEDATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS VARCHAR2(3) DEFAULT 'Y' NOT NULL
);

--NOTICE 시퀀스
CREATE SEQUENCE SEQ_NNO
START WITH 15001
INCREMENT BY 1
MAXVALUE 20000
NOCYCLE
NOCACHE;

---------------------더미데이터-----------------------
-- 멤버
INSERT INTO MEMBER VALUES(1, 'admin@naver.com', '1234' ,'관리자', '음악', 1,
        '010-1111-0000', '서울시 강남구', 'Y', 'M', '4', 'resources/memberProfileImg/userDefaultProFile.png', NULL, NULL);
INSERT INTO MEMBER VALUES(SEQ_MNO.NEXTVAL, 'user01@naver.com','1234' ,'홍길동', '음악', 1, 
        '010-1111-1111', '서울시 송파구', 'Y', 'M', '4', 'resources/memberProfileImg/userDefaultProFile.png', NULL, NULL);

INSERT INTO MEMBER(
            MEM_NO,
			MEM_EMAIL,
			MEM_PWD,
			MEM_NAME,
			MEM_CONCERN,
			PHONE,
			MEM_GEN,
            INTRO
		)
		VALUES(
            SEQ_MNO.NEXTVAL,
			'aaa@naver.com',
			'1111',
			'김개똥',
			'요리',
			'010-2222-2222',
			'M',
            NULL
		);
--카테고리
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '음악');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '운동');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '게임');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '미술');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '댄스');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '요리');

--프로
INSERT INTO PROFESSIONAL VALUES(SEQ_PNO.NEXTVAL, '피아니스트', 200, 2);

--게시판(보드)
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '음악레슨합니다', '음악 정말 즐겁게 알려드려요1', 50000, 1, '2020-01-01', 'Y', 2, 200);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '음악레슨합니다', '음악 정말 즐겁게 알려드려요2', 50000, 1, '2020-02-01', 'Y', 2, 200);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '음악레슨합니다', '음악 정말 즐겁게 알려드려요3', 50000, 1, '2020-03-01', 'Y', 2, 200);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '음악레슨합니다', '음악 정말 즐겁게 알려드려요4', 50000, 1, '2020-04-01', 'Y', 2, 200);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '음악레슨합니다', '음악 정말 즐겁게 알려드려요5', 50000, 1, '2020-05-01', 'Y', 2, 200);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '음악레슨합니다', '음악 정말 즐겁게 알려드려요6', 50000, 1, '2020-06-01', 'Y', 2, 200);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '음악레슨합니다', '음악 정말 즐겁게 알려드려요7', 50000, 1, '2020-07-01', 'Y', 2, 200);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '커뮤니티용 음악레슨합니다1', '커뮤니티용 음악 정말 즐겁게 알려드려요', 50000, 3, '2020-01-02', 'Y', 2, 200);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '얼마예요1', '커뮤니티용 음악 정말 즐겁게 알려드려요', 40000, 4, '2020-01-03', 'Y', 2, 200);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '함께해요1', '커뮤니티용 음악 정말 즐겁게 알려드려요', 40000, 5, '2020-01-04', 'Y', 2, 200);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '궁금해요2', '커뮤니티용 음악 정말 즐겁게 알려드려요', 40000, 3, '2020-01-05', 'Y', 2, 200);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '얼마예요2', '커뮤니티용 음악 정말 즐겁게 알려드려요', 40000, 4, '2020-01-06', 'Y', 2, 200);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '함께2', '커뮤니티용 음악 정말 즐겁게 알려드려요', 40000, 5, '2020-01-07', 'Y', 2, 200);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '커뮤니티용 페이징처리', '커뮤니티용 음악 정말 즐겁게 알려드려요', 40000, 3, '2020-01-08', 'Y', 2, 200);
-- ATTACHEMT 사진
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '33', '4' , 'Y' ,1000);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '33', '4' , 'Y' ,1001);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '33', '4' , 'Y' ,1002);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '33', '4' , 'Y' ,1003);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '33', '4' , 'Y' ,1004);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '33', '4' , 'Y' ,1005);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '33', '4' , 'Y' ,1006);
-- NOTICE
INSERT INTO NOTICE VALUES(SEQ_NNO.NEXTVAL, '필독', '품앗이에 대하여', '품앗이 사이트는 전문가 및 준전문가와 수요자의 매칭을 해주는 사이트입니다.', '2020-01-01', 'Y');
INSERT INTO NOTICE VALUES(SEQ_NNO.NEXTVAL, '필독', '품앗이 채용 사칭 스미싱 문자 주의', '다른 번호 외에 전화를 걸지 말아 주시고,
소비자 보호를 위해 스미싱 사이트에 접속하지 말아주시길 당부 드립니다.', '2020-01-01', 'Y');
INSERT INTO NOTICE VALUES(SEQ_NNO.NEXTVAL, '공지', '품앗이 서비스 점검안내', '사이트 및 서버 점검이 진행 될 예정입니다.
점검시간 동안 품앗이 사이트 서비스 이용이 불가능하오니 양해 부탁드립니다.', '2020-01-01', 'Y');
INSERT INTO NOTICE VALUES(SEQ_NNO.NEXTVAL, '공지', '품앗이 사기 당했을 경우', '사기 당했을 경우 신고바랍니다.', '2020-01-01', 'Y');
INSERT INTO NOTICE VALUES(SEQ_NNO.NEXTVAL, '공지', '품앗이 현피뜰 경우', '금일은 서비스 점검으로 인해 오후에 사용이 어려울 수 있습니다.
고객놈들께서는 참고하시고 이용을 하든지 말든지 진짜 귀찮게 굴지 마시고
알아서 하시길...', SYSDATE, 'Y');
INSERT INTO NOTICE VALUES(SEQ_NNO.NEXTVAL, '공지', '품앗이생활은 감옥생활', '품앗이 생활 한번 시작하면은 못빠져나간다', SYSDATE, 'Y');
---트랜잭션
commit;