--접속유저의 모든 테이블 삭제
BEGIN
    FOR C IN (SELECT TABLE_NAME FROM USER_TABLES) LOOP
    EXECUTE IMMEDIATE ('DROP TABLE '||C.TABLE_NAME||' CASCADE CONSTRAINTS');
    END LOOP;
END;
/

--접속유저의 모든 시퀀스 삭제
BEGIN
FOR C IN (SELECT * FROM USER_SEQUENCES) LOOP
  EXECUTE IMMEDIATE 'DROP SEQUENCE '||C.SEQUENCE_NAME;
END LOOP;
END;
/

--접속유저의 모든 뷰 삭제
BEGIN
FOR C IN (SELECT * FROM USER_VIEWS) LOOP
  EXECUTE IMMEDIATE 'DROP VIEW '||C.VIEW_NAME;
END LOOP;
END;
/
-----------테이블----------
--SKILL 테이블
CREATE TABLE SKILL(
    SKILL_NO NUMBER PRIMARY KEY,
    SKILL_NAME VARCHAR2(100)
);

--SKILL 시퀀스
CREATE SEQUENCE SEQ_SKILL_NO
START WITH 333300
INCREMENT BY 1
MAXVALUE 334999
NOCYCLE
NOCACHE;

-- MEMBER(유저/회원)테이블
CREATE TABLE MEMBER(
    MEM_NO NUMBER PRIMARY KEY,
    MEM_EMAIL VARCHAR2(60) UNIQUE,
    MEM_PWD VARCHAR2(60) NULL,
    MEM_NAME VARCHAR2(60) NOT NULL,
    MEM_CONCERN VARCHAR2(30),
    MEM_PRO NUMBER DEFAULT 1 NOT NULL,
    PHONE VARCHAR2(30) NOT NULL,
    LOCATION VARCHAR2(100),
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    MEM_GEN VARCHAR2(10) NOT NULL CHECK(MEM_GEN IN ('M','F')), 
    POINT NUMBER,
    FILE_PATH VARCHAR2(3000) DEFAULT 'resources/memberProfileImg/userDefaultProFile.png',
    ACCOUNT NUMBER DEFAULT 0,
    INTRO VARCHAR2(3000),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    SKILL_NO NUMBER REFERENCES SKILL(SKILL_NO)
);

--멤버 시퀀스
CREATE SEQUENCE SEQ_MNO
START WITH 2
INCREMENT BY 1
MAXVALUE 99
NOCYCLE
NOCACHE;

----SORT(분류(카테고리상세))테이블
--CREATE TABLE SORT(
--    SORT_NO NUMBER PRIMARY KEY,
--    SORT_NAME VARCHAR2(300) NOT NULL
--);
--
----SORT 시퀀스
--CREATE SEQUENCE SEQ_SNO
--START WITH 100
--INCREMENT BY 1
--MAXVALUE 199
--NOCYCLE
--NOCACHE;

--CATEGORY(카테고리)테이블
CREATE TABLE CATEGORY(
    CATEGORY_NO NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(200) NOT NULL
);

--CATEGORY 시퀀스
CREATE SEQUENCE SEQ_CNO
START WITH 200
INCREMENT BY 1
MAXVALUE 299
NOCYCLE
NOCACHE;

-- BOARD(게시판)테이블
CREATE TABLE BOARD(
  BOARD_NO NUMBER PRIMARY KEY,
  BOARD_TITLE VARCHAR2(150) NOT NULL,
  BOARD_CONTENT VARCHAR2(3000) NOT NULL,
  PRICE NUMBER,
  BOARD_TYPE NUMBER CHECK(BOARD_TYPE IN(1, 2, 3, 4, 5)),
  CREATEDATE DATE DEFAULT SYSDATE NOT NULL,
  STATUS VARCHAR2(3) DEFAULT 'Y',
  MEM_NO NUMBER REFERENCES MEMBER(MEM_NO),
  CATEGORY_NO NUMBER REFERENCES CATEGORY(CATEGORY_NO),
  LIKEY_COUNT NUMBER DEFAULT 0,
  VIEW_COUNT NUMBER DEFAULT 0
);

--BOARD 시퀀스
CREATE SEQUENCE SEQ_BNO
START WITH 1000
INCREMENT BY 1
MAXVALUE 9999
NOCYCLE
NOCACHE;

--REPLY 테이블 생성
CREATE TABLE REPLY(
    REPLY_NO NUMBER PRIMARY KEY,
    REPLY_CONTENT VARCHAR2(3000) NOT NULL,
    CREATEDATE DATE DEFAULT SYSDATE NOT NULL,
    MEM_NO NUMBER REFERENCES MEMBER(MEM_NO),
    BOARD_NO NUMBER REFERENCES BOARD(BOARD_NO),
    STATUS VARCHAR2(3) DEFAULT 'Y',
    RELIKEY_COUNT NUMBER DEFAULT 0
);

-- REPLY 시퀀스
CREATE SEQUENCE SEQ_RNO
START WITH 20001
INCREMENT BY 1
MAXVALUE 25000
NOCYCLE
NOCACHE;

--ATTACHMENT테이블
CREATE TABLE ATTACHMENT(
    ATT_NO NUMBER PRIMARY KEY,
    ORIGIN_NAME VARCHAR2(2000) NOT NULL,
    CHANGE_NAME VARCHAR2(2000) NOT NULL,
    FILE_PATH VARCHAR2(3000),
    STATUS VARCHAR2(3) DEFAULT 'Y',
    BOARD_NO NUMBER REFERENCES BOARD(BOARD_NO),
    FILE_LEVEL NUMBER DEFAULT 0
);

--ATTACHMENT 시퀀스
CREATE SEQUENCE SEQ_ANO
START WITH 10000
INCREMENT BY 1
MAXVALUE 15000
NOCYCLE
NOCACHE;

--NOTICE 공지사항 테이블
CREATE TABLE NOTICE(
    NOTICE_NO NUMBER PRIMARY KEY,
    NOTICE_TYPE VARCHAR2(30) DEFAULT '공지' NOT NULL,
    NOTICE_TITLE VARCHAR2(2000) NOT NULL,
    NOTICE_CONTENT VARCHAR2(2000) NOT NULL,
    CREATEDATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS VARCHAR2(3) DEFAULT 'Y' NOT NULL
);

--NOTICE 시퀀스
CREATE SEQUENCE SEQ_NNO
START WITH 15001
INCREMENT BY 1
MAXVALUE 20000
NOCYCLE
NOCACHE;

--SCHEDULE(요청) 테이블
CREATE TABLE SCHEDULE(
    SCHE_NO NUMBER PRIMARY KEY,
    SCHE_TITLE VARCHAR2(2000) NOT NULL,
    SCHE_CONTENT VARCHAR2(2000) NOT NULL,
    BOARD_NO NUMBER REFERENCES BOARD(BOARD_NO),
    FROM_MNO NUMBER REFERENCES MEMBER(MEM_NO),
    TO_MNO NUMBER REFERENCES MEMBER(MEM_NO),
    CATEGORY_NO NUMBER REFERENCES CATEGORY(CATEGORY_NO),
    STATUS VARCHAR2(3) DEFAULT 'Y' NOT NULL,
    CREATEDATE DATE DEFAULT SYSDATE NOT NULL,
    LOCATION VARCHAR2(2000) NOT NULL
);

-- SCHEDULE(요청)시퀀스
CREATE SEQUENCE SEQ_SNO START WITH 100000 INCREMENT BY 1 MAXVALUE 109999 NOCYCLE NOCACHE;

-- AUTHENTICATE(이메일인증 난수)테이블
CREATE TABLE AUTHENTICATE(
    AUTH_NO NUMBER PRIMARY KEY,
    AUTH_EMAIL VARCHAR2(1000) NOT NULL,
    AUTH_RANDOM NUMBER NOT NULL,
    CREATEDATE DATE DEFAULT SYSDATE NOT NULL
);

-- AUTHENTICATE 시퀀스
CREATE SEQUENCE SEQ_AUNO
START WITH 1000000
INCREMENT BY 1
MAXVALUE 1050000
NOCYCLE
NOCACHE;


--채팅방 테이블 생성
CREATE TABLE CHATROOM(
    RECEIVER_NO NUMBER REFERENCES MEMBER(MEM_NO),
    RECEIVER_NAME VARCHAR2(200) NOT NULL,
    STATUS CHAR(1) DEFAULT 'Y',
    SENDER_NO NUMBER,
    SENDER_NAME VARCHAR2(200) NOT NULL,
    MEM_COUNT NUMBER DEFAULT 1,
    LAST_MSG VARCHAR2(4000),
    LAST_CHAT_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    CHAT_COUNT NUMBER
);

--채팅방 시퀀스
CREATE SEQUENCE SEQ_CRNO
START WITH 1
INCREMENT BY 1
MAXVALUE 9999
NOCYCLE
NOCACHE;

--메시지 테이블 생성
CREATE TABLE CHATMSG(
    MSG_NO NUMBER PRIMARY KEY,
    MSG VARCHAR2(4000) NOT NULL,
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    SENDER_NO NUMBER REFERENCES MEMBER(MEM_NO),
    RECEIVER_NO NUMBER REFERENCES MEMBER(MEM_NO)
);

--메시지 시퀀스
CREATE SEQUENCE SEQ_MSGNO
START WITH 1
INCREMENT BY 1
MAXVALUE 9999
NOCYCLE
NOCACHE;

CREATE TABLE LIKEY(
LIKEY_NO NUMBER PRIMARY KEY,
BOARD_NO NUMBER NOT NULL,
MEM_NO NUMBER NOT NULL,
LISTATUS VARCHAR2(2) DEFAULT 'N'
);

-- 좋아요 시퀀스
CREATE SEQUENCE SEQ_LNO
START WITH 300000
INCREMENT BY 1
MAXVALUE 400000
NOCYCLE
NOCACHE;

CREATE TABLE REPLY_LIKEY(
RELIKEY_NO NUMBER PRIMARY KEY,
REPLY_NO NUMBER NOT NULL,
BOARD_NO NUMBER NOT NULL,
MEM_NO NUMBER NOT NULL,
RE_LISTATUS VARCHAR2(2) DEFAULT 'N'
);

-- 좋아요 시퀀스
CREATE SEQUENCE SEQ_RLNO
START WITH 400001
INCREMENT BY 1
MAXVALUE 500000
NOCYCLE
NOCACHE;

--PAY테이블생성
CREATE TABLE PAY (
    PAY_NO NUMBER PRIMARY KEY,
    PRICE NUMBER NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    MEM_NO NUMBER REFERENCES MEMBER(MEM_NO)
);

--PAY 시퀀스
CREATE SEQUENCE SEQ_PAY_NO
START WITH 700000
INCREMENT BY 1
MAXVALUE 710000
NOCYCLE
NOCACHE;

--REASON테이블 탈퇴사유
CREATE TABLE REASON (
    MEM_NO NUMBER REFERENCES MEMBER (MEM_NO) UNIQUE,
    REA_CONTENT VARCHAR2(3000) NOT NULL,
    RETIRE_DATE DATE DEFAULT SYSDATE
);

--신고 테이블
CREATE TABLE REPORT (
    REPORT_NO NUMBER PRIMARY KEY,
    REPORT_TITLE VARCHAR2(100),
    REPORT_CONTENT VARCHAR2(3000),
    CREATEDATE DATE DEFAULT SYSDATE,
    MEM_NO NUMBER REFERENCES MEMBER (MEM_NO),
    ADMIN_COMENT VARCHAR2(1000),
    STATUS VARCHAR2(3) DEFAULT 'Y'
);

--REPORT 시퀀스
CREATE SEQUENCE SEQ_RPNO
START WITH 400000
INCREMENT BY 1
MAXVALUE 410000
NOCYCLE
NOCACHE;

---------------------더미데이터-----------------------
--SKILL
--행 0
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'선택 없음');
--행 1
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'세무사');
--행 2
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'관세사');
--행 3
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'관광통역안내사(영어)');
--행 4
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'국내여행안내사');
--행 5
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'호텔경영사');
--행 6
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'호텔관리사');
--행 7
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'관광통역안내사(불어)');
--행 8
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'정수시설운영관리사3급');
--행 9
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'정수시설운영관리사2급');
--행 10
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'정수시설운영관리사1급');
--행 11
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'기계경비지도사');
--행 12
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'일반경비지도사');
--행 13
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기술자(식물보호)');
--행 14
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기술자(보존과학)');
--행 15
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'관광통역안내사(독어)');
--행 16
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'관광통역안내사(스페인어)');
--행 17
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'관광통역안내사(러시아어)');
--행 18
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'검량사');
--행 19
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'감정사');
--행 20
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'관광통역안내사(일본어)');
--행 21
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'한국어교육능력검정시험');
--행 22
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기술자(조경)');
--행 23
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기술자(실측설계)');
--행 24
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기술자(보수)');
--행 25
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기술자(단청)');
--행 26
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'가맹거래사');
--행 27
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'박물관및미술관준학예사');
--행 28
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'사회복지사 1급');
--행 29
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'변리사');
--행 30
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'방사성동위원소취급자일반면허');
--행 31
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'공인노무사');
--행 32
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'물류관리사');
--행 33
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'농산물품질관리사');
--행 34
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'주택관리사보');
--행 35
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'소방시설관리사');
--행 36
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'소방안전교육사');
--행 37
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'공인중개사');
--행 38
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'경영지도사(1차공통)');
--행 39
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'기술지도사(1차공통)');
--행 40
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'검수사');
--행 41
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'관광통역안내사(중국어)');
--행 42
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'호텔서비스사');
--행 43
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'방사성동위원소취급자특수면허');
--행 44
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'방사선취급감독자면허');
--행 45
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'경영지도사(인적자원관리)');
--행 46
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'경영지도사(재무관리)');
--행 47
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'경영지도사(생산관리)');
--행 48
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'경영지도사(마케팅)');
--행 49
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(대목수)');
--행 50'
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(소목수)');
--행 51
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(가공석공)');
--행 52
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(쌓기석공)');
--행 53
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(화공)');
--행 54
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(드잡이공)');
--행 55
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(번와와공)');
--행 56
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(제작와공)');
--행 57
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(한식미장공)');
--행 58
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(철물공)');
--행 59
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(목조각공)');
--행 60
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(석조각공)');
--행 61
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(칠공)');
--행 62
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(도금공)');
--행 63
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(표구공)');
--행 64
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(조경공)');
--행 65
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(세척공)');
--행 66
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(보존처리공)');
--행 67
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(식물보호공)');
--행 68
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(실측설계사보)');
--행 69
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(박제및표본제작공)');
--행 70
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'감정평가사');
--행 71
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(훈증공)');
--행 72
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'도자공예기능사');
--행 73
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'중식조리기능사');
--행 74
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'복어조리기능사');
--행 75
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'조주기능사');
--행 76
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'피아노조율기능사');
--행 77
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'이용사');
--행 78
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'한식조리기능사');
--행 79
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'양식조리기능사');
--행 80
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'일식조리기능사');
--행 81
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'신발류제조기능사');
--행 82
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'환경기능사');
--행 83
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'콘크리트기능사');
--행 84
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'자기비파괴검사기능사');
--행 85
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'침투비파괴검사기능사');
--행 86
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'한복기능사');
--행 87
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'정보기기운용기능사');
--행 88
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전산응용조선제도기능사');
--행 89
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'선체건조기능사');
--행 90
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'염색기능사(침염)');
--행 91
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'정보처리기능사');
--행 92
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'염색기능사(날염)');
--행 93
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'석공기능사');
--행 94
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'철도토목기능사');
--행 95
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전자계산기기능사');
--행 96
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'화학분석기능사');
--행 97
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'도배기능사');
--행 98
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전자기기기능사');
--행 99
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'타일기능사');
--행 100
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건축도장기능사');
--행 101
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'석공예기능사');
--행 102
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'유리시공기능사');
--행 103
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'실내건축기능사');
--행 104
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'온수온돌기능사');
--행 105
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'거푸집기능사');
--행 106
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'비계기능사');
--행 107
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'귀금속가공기능사');
--행 108
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'방사선비파괴검사기능사');
--행 109
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'항공사진기능사');
--행 110
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'광학기능사');
--행 111
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'지도제작기능사');
--행 112
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'초음파비파괴검사기능사');
--행 113
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건설재료시험기능사');
--행 114
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'가구제작기능사');
--행 115
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'금속도장기능사');
--행 116
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'제과기능사');
--행 117
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'제빵기능사');
--행 118
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'광고도장기능사');
--행 119
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'보석가공기능사');
--행 120
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'조경기능사');
--행 121
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'도화기능사');
--행 122
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'보석감정사');
--행 123
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'지게차운전기능사');
--행 124
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'롤러운전기능사');
--행 125
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'양화장치운전기능사');
--행 126
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'승강기기능사');
--행 127
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'세탁기능사');
--행 128
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'화약취급기능사');
--행 129
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'수산양식기능사');
--행 130
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'로더운전기능사');
--행 131
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'목공예기능사');
--행 132
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'축산기능사');
--행 133
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'식육처리기능사');
--행 134
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'버섯종균기능사');
--행 135
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'기중기운전기능사');
--행 136
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'굴착기운전기능사');
--행 137
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'불도저운전기능사');
--행 138
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'산림기능사');
--행 139
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'잠수기능사');
--행 140
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'종자기능사');
--행 141
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'지적기능사');
--행 142
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'임업종묘기능사');
--행 143
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'철근기능사');
--행 144
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'사진기능사');
--행 145
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'컴퓨터그래픽스운용기능사');
--행 146
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'기계가공조립기능사');
--행 147
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'공조냉동기계기능사');
--행 148
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'가스기능사');
--행 149
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'직업상담사2급');
--행 150
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'사회조사분석사1급');
--행 151
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'사회조사분석사2급');
--행 152
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'기계정비기능사');
--행 153
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건축목공기능사');
--행 154
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'금속재창호기능사');
--행 155
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'미장기능사');
--행 156
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'열처리기능사');
--행 157
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'방수기능사');
--행 158
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전산응용건축제도기능사');
--행 159
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'조적기능사');
--행 160
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'양식조리산업기사');
--행 161
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'일식조리산업기사');
--행 162
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'중식조리산업기사');
--행 163
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'복어조리산업기사');
--행 164
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'측량기능사');
--행 165
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'축로기능사');
--행 166
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'농기계정비기능사');
--행 167
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'원형기능사');
--행 168
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'항공기관정비기능사');
--행 169
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'항공장비정비기능사');
--행 170
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'항공전자정비기능사');
--행 171
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'자동차정비기능사');
--행 172
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'주조기능사');
--행 173
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'자동차차체수리기능사');
--행 174
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'항공기체정비기능사');
--행 175
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'금속재료시험기능사');
--행 176
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'제선기능사');
--행 177
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전산응용기계제도기능사');
--행 178
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'정밀측정기능사');
--행 179
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'농기계운전기능사');
--행 180
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건축일반시공기능장');
--행 181
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'주조기능장');
--행 182
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'표면처리기능장');
--행 183
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'자동차정비기능장');
--행 184
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건설기계정비기능장');
--행 185
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'교통산업기사');
--행 186
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'귀금속가공산업기사');
--행 187
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'어로산업기사');
--행 188
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'철도차량정비기능장');
--행 189
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'금형제작기능장');
--행 190
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'배관기능장');
--행 191
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'산업위생관리산업기사');
--행 192
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'판금제관기능장');
--행 193
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'용접기능장');
--행 194
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'폐기물처리산업기사');
--행 195
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'포장산업기사');
--행 196
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'제품디자인산업기사');
--행 197
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'공조냉동기계산업기사');
--행 198
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'화약류제조산업기사');
--행 199
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'실내건축산업기사');
--행 200
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'정보처리산업기사');
--행 201
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건설재료시험산업기사');
--행 202
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'방사선비파괴검사산업기사');
--행 203
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'한식조리산업기사');
--행 204
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'패션디자인산업기사');
--행 205
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'섬유디자인산업기사');
--행 206
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전산응용토목제도기능사');
--행 207
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'조리기능장');
--행 208
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'제과기능장');
--행 209
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'미용장');
--행 210
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'이용장');
--행 211
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'귀금속가공기능장');
--행 212
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건축목재시공기능장');
--행 213
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'초음파비파괴검사산업기사');
--행 214
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'침투비파괴검사산업기사');
--행 215
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'기계가공기능장');
--행 216
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'가스기능장');
--행 217
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전자기기기능장');
--행 218
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'소방설비산업기사(전기분야)');
--행 219
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'소음진동산업기사');
--행 220
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'금속재료기능장');
--행 221
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'제선기능장');
--행 222
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'제강기능장');
--행 223
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'압연기능장');
--행 224
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'피아노조율산업기사');
--행 225
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'소방설비산업기사(기계분야)');
--행 226
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'자기비파괴검사산업기사');
--행 227
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'에너지관리기능장');
--행 228
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'농업기계산업기사');
--행 229
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'사출금형산업기사');
--행 230
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'공조냉동기계기사');
--행 231
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'프레스금형산업기사');
--행 232
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'철도차량산업기사');
--행 233
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'소방설비기사(기계분야)');
--행 234
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'대기환경기사');
--행 235
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'용접산업기사');
--행 236
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'가스기사');
--행 237
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건축기사');
--행 238
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건축설비기사');
--행 239
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'폐기물처리기사');
--행 240
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'기계조립산업기사');
--행 241
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'축산기사');
--행 242
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'임산가공기사');
--행 243
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'식품기사');
--행 244
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'수산제조기사');
--행 245
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'승강기기사');
--행 246
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'종자기사');
--행 247
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'포장기사');
--행 248
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'제품디자인기사');
--행 249
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'시설원예기사');
--행 250
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'시각디자인기사');
--행 251
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'바이오화학제품제조기사');
--행 252
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'폐기물처리기술사');
--행 253
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'화약류관리기사');
--행 254
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'산업위생관리기사');
--행 255
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'해양공학기사');
--행 256
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'광학기사');
--행 257
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'산업안전기사');
--행 258
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건설안전기사');
--행 259
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'측량및지형공간정보기사');
--행 260
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'프레스금형설계기사');
--행 261
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'철도차량기사');
--행 262
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'지적기사');
--행 263
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'인쇄기사');
--행 264
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'해양환경기사');
--행 265
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'해양자원개발기사');
--행 266
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건설기계설비기사');
--행 267
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건설기계정비기사');
--행 268
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'일반기계기사');
--행 269
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'용접기사');
--행 270
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'도시계획기사');
--행 271
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'조경기사');
--행 272
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'농업기계기사');
--행 273
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'사출금형설계기사');
--행 274
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'소음진동기술사');
--행 275
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'농화학기술사');
--행 276
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'정보처리기사');
--행 277
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전자계산기기사');
--행 278
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전자계산기조직응용기사');
--행 279
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'실내건축기사');
--행 280
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'교통기술사');
--행 281
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'수산양식기사');
--행 282
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'침투비파괴검사기사');
--행 283
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'와전류비파괴검사기사');
--행 284
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'수질환경기사');
--행 285
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'소음진동기사');
--행 286
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'누설비파괴검사기사');
--행 287
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'기상기사');
--행 288
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'의류기사');
--행 289
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'소방설비기사(전기분야)');
--행 290
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'자기비파괴검사기사');
--행 291
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'식물보호기사');
--행 292
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'임업종묘기사');
--행 293
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건축일반시공산업기사');
--행 294
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건축목공산업기사');
--행 295
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'대기환경산업기사');
--행 296
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'수질환경산업기사');
--행 297
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'조선산업기사');
--행 298
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'식물보호산업기사');
--행 299
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'수산양식산업기사');
--행 300
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'잠수산업기사');
--행 301
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건축산업기사');
--행 302
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건축설비산업기사');
--행 303
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전기산업기사');
--행 304
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전기공사산업기사');
--행 305
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'산림산업기사');
--행 306
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'축산산업기사');
--행 307
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'임산가공산업기사');
--행 308
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'식품산업기사');
--행 309
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'철도신호산업기사');
--행 310
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전자산업기사');
--행 311
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'화약류관리산업기사');
--행 312
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'종자산업기사');
--행 313
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'가스산업기사');
--행 314
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'항공산업기사');
--행 315
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'토목산업기사');
--행 316
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'주조산업기사');
--행 317
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'표면처리산업기사');
--행 318
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'시각디자인산업기사');
--행 319
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건설안전산업기사');
--행 320
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'인쇄산업기사');
--행 321
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'승강기산업기사');
--행 322
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'측량및지형공간정보산업기사');
--행 323
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'지적산업기사');
--행 324
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'금속재료산업기사');
--행 325
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'정밀측정산업기사');
--행 326
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'해양조사산업기사');
--행 327
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'산업안전산업기사');
--행 328
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'조경산업기사');
--행 329
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'자동차정비산업기사');
--행 330
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건설기계설비산업기사');
--행 331
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'배관산업기사');
--행 332
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'방사선비파괴검사기사');
--행 333
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'초음파비파괴검사기사');
--행 334
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'철도신호기사');
--행 335
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전기철도기사');
--행 336
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건설기계정비산업기사');
--행 337
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'기계설계산업기사');
--행 338
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건설재료시험기사');
--행 339
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'교통기사');
--행 340
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'철도토목기사');
--행 341
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'생산자동화산업기사');
--행 342
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'기계정비산업기사');
--행 343
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'임상심리사1급');
--행 344
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'임상심리사2급');
--행 345
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'텔레마케팅관리사');
--행 346
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'멀티미디어콘텐츠제작전문가');
--행 347
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전자응용기술사');
--행 348
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'발송배전기술사');
--행 349
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'소방기술사');
--행 350
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'천장크레인운전기능사');
--행 351
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'동력기계정비기능사');
--행 352
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'응용지질기사');
--행 353
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'사무자동화산업기사');
--행 354
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'플라스틱창호기능사');
--행 355
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'소비자전문상담사1급');
--행 356
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전기응용기술사');
--행 357
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'철도신호기술사');
--행 358
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'콘크리트기사');
--행 359
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'콘크리트산업기사');
--행 360
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'화훼장식기능사');
--행 361
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'웹디자인기능사');
--행 362
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'자연생태복원기사');
--행 363
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'자연생태복원산업기사');
--행 364
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'토양환경기사');
--행 365
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'토양환경기술사');
--행 366
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'자연환경관리기술사');
--행 367
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'궤도장비정비기사');
--행 368
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'궤도장비정비산업기사');
--행 369
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'궤도장비정비기능사');
--행 370
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'금속재료기술사');
--행 371
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'표면처리기술사');
--행 372
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'금속가공기술사');
--행 373
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'차량기술사');
--행 374
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'유기농업기사');
--행 375
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'유기농업산업기사');
--행 376
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'생물분류기사(식물)');
--행 377
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'생물분류기사(동물)');
--행 378
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'인간공학기술사');
--행 379
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'인간공학기사');
--행 380
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'공조냉동기계기술사');
--행 381
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건설기계기술사');
--행 382
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'대기관리기술사');
--행 383
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'수질관리기술사');
--행 384
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'축산기술사');
--행 385
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'항공기사');
--행 386
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'토목기사');
--행 387
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'수산제조기술사');
--행 388
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'제품디자인기술사');
--행 389
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'종자기술사');
--행 390
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'시설원예기술사');
--행 391
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'세라믹기술사');
--행 392
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'식품기술사');
--행 393
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'토목품질시험기술사');
--행 394
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전기기사');
--행 395
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전기공사기사');
--행 396
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전자기사');
--행 397
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'비파괴검사기술사');
--행 398
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'산업위생관리기술사');
--행 399
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'가스기술사');
--행 400
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'공장관리기술사');
--행 401
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'품질관리기술사');
--행 402
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'화공기사');
--행 403
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'화약류제조기사');
--행 404
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'포장기술사');
--행 405
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'기계안전기술사');
--행 406
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'화공안전기술사');
--행 407
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전기안전기술사');
--행 408
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건설안전기술사');
--행 409
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'측량및지형공간정보기술사');
--행 410
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'지적기술사');
--행 411
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'해양기술사');
--행 412
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'수산양식기술사');
--행 413
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'어로기술사');
--행 414
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'도시계획기술사');
--행 415
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전자캐드기능사');
--행 416
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'자동차정비기사');
--행 417
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'정보관리기술사');
--행 418
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'조경기술사');
--행 419
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'용접기술사');
--행 420
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'금형기술사');
--행 421
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'의류기술사');
--행 422
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'화약류관리기술사');
--행 423
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건축품질시험기술사');
--행 424
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건축구조기술사');
--행 425
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건축기계설비기술사');
--행 426
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건축전기설비기술사');
--행 427
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건축시공기술사');
--행 428
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전기철도기술사');
--행 429
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'수자원개발기술사');
--행 430
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'상하수도기술사');
--행 431
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'농어업토목기술사');
--행 432
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'토목시공기술사');
--행 433
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'토질및기초기술사');
--행 434
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'지질및지반기술사');
--행 435
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'토목구조기술사');
--행 436
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'항만및해안기술사');
--행 437
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'도로및공항기술사');
--행 438
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'철도기술사');
--행 439
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'철도차량기술사');
--행 440
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'생산자동화기능사');
--행 441
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'공유압기능사');
--행 442
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'패션머천다이징산업기사');
--행 443
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'항로표지기사');
--행 444
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'항로표지산업기사');
--행 445
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'항로표지기능사');
--행 446
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'컬러리스트기사');
--행 447
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'컬러리스트산업기사');
--행 448
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'제품응용모델링기능사');
--행 449
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'기상예보기술사');
--행 450
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'항공기체기술사');
--행 451
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'항공기관기술사');
--행 452
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전자출판기능사');
--행 453
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'컨벤션기획사1급');
--행 454
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'소비자전문상담사2급');
--행 455
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전기기능장');
--행 456
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'배관기능사');
--행 457
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'표면처리기능사');
--행 458
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'인쇄기능사');
--행 459
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'식품가공기능사');
--행 460
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전기기능사');
--행 461
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'원예기능사');
--행 462
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'철도운송산업기사');
--행 463
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'산림기술사');
--행 464
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'금속재료기사');
--행 465
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전자계산기제어산업기사');
--행 466
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'컴퓨터응용선반기능사');
--행 467
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'컴퓨터응용밀링기능사');
--행 468
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'철도차량정비기능사');
--행 469
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'압연기능사');
--행 470
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'피복아크용접기능사');
--행 471
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'어업생산관리기사');
--행 472
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'에너지관리기사');
--행 473
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'에너지관리산업기사');
--행 474
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'화훼장식기사');
--행 475
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'스포츠경영관리사');
--행 476
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'산업계측제어기술사');
--행 477
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'위험물산업기사');
--행 478
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'위험물기능장');
--행 479
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'유기농업기능사');
--행 480
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'자동차보수도장기능사');
--행 481
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'설비보전기사');
--행 482
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'설비보전기능사');
--행 483
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전자부품장착산업기사');
--행 484
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전자부품장착기능사');
--행 485
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'화학분석기사');
--행 486
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'타워크레인운전기능사');
--행 487
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'반도체설계산업기사');
--행 488
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'컨벤션기획사2급');
--행 489
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'산업기계설비기술사');
--행 490
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'화공기술사');
--행 491
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'조선기술사');
--행 492
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'기계설계기사');
--행 493
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'직업상담사1급');
--행 494
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'품질경영기사');
--행 495
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'의료전자기능사');
--행 496
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'의공산업기사');
--행 497
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'의공기사');
--행 498
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'미용사(일반)');
--행 499
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'미용사(피부)');
--행 500
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'전기철도산업기사');
--행 501
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'산림기사');
--행 502
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'판금제관산업기사');
--행 503
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'컴퓨터응용가공산업기사');
--행 504
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'품질경영산업기사');
--행 505
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'경매사(수산)');
--행 506
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'경매사(축산)');
--행 507
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'경매사(약용)');
--행 508
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'관광통역안내사(태국어)');
--행 509
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'관광통역안내사(아랍어)');
--행 510
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'관광통역안내사(베트남어)');
--행 511
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'관광통역안내사(말레이/인도네시아어)');
--행 512
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'경매사(화훼)');
--행 513
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'경매사(양곡)');
--행 514
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'관광통역안내사(이탈리아어)');
--행 515
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'경매사(청과)');
--행 516
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'1급 청소년지도사');
--행 517
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'2급 청소년지도사');
--행 518
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'3급 청소년지도사');
--행 519
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'1급 청소년상담사');
--행 520
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'2급 청소년상담사');
--행 521
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'3급 청소년상담사');
--행 522
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'기계기술사');
--행 523
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'컴퓨터시스템응용기술사');
--행 524
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'섬유기술사');
--행 525
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'금형기능사');
--행 526
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'건설기계정비기능사');
--행 527
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'판금제관기능사');
--행 528
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'양복기능사');
--행 529
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'제강기능사');
--행 530
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'기상감정기사');
--행 531
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'재료조직평가산업기사');
--행 532
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'섬유기사');
--행 533
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'에너지관리기능사');
--행 534
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'양장기능사');
--행 535
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'임산가공기능사');
--행 536
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'위험물기능사');
--행 537
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'컨테이너크레인운전기능사');
--행 538
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'섬유산업기사');
--행 539
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'철도전기신호기능사');
--행 540
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'광학기기산업기사');
--행 541
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'금속제련기술사');
--행 542
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'산업안전지도사(건설안전)');
--행 543
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'산업안전지도사(화공안전)');
--행 544
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'신재생에너지발전설비기사(태양광)');
--행 545
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'신재생에너지발전설비기능사(태양광)');
--행 546
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'그린전동자동차기사');
--행 547
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(온돌공)');
--행 548
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'문화재수리기능자(모사공)');
--행 549
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'수산물품질관리사');
--행 550
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'산업보건지도사(직업환경의학)');
--행 551
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'산업보건지도사(산업위생공학)');
--행 552
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'임베디드기사');
--행 553
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'국제의료관광코디네이터');
--행 554
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'반도체장비유지보수기능사');
--행 555
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'미용사(네일)');
--행 556
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'미용사(메이크업)');
--행 557
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'산업안전지도사(기계안전)');
--행 558
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'외국어번역행정사');
--행 559
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'손해평가사');
--행 560
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'신재생에너지발전설비산업기사(태양광)');
--행 561
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'화재감식평가산업기사');
--행 562
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'해사행정사');
--행 563
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'천공기운전기능사');
--행 564
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'온실가스관리기사');
--행 565
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'산업안전지도사(전기안전)');
--행 566
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'화재감식평가기사');
--행 567
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'방수산업기사');
--행 568
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'일반행정사');
--행 569
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'온실가스관리산업기사');
--행 570
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'이산화탄소가스아크용접기능사');
--행 571
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'기술지도사(정보기술관리)');
--행 572
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'조선선체기사');
--행 573
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'조선의장기사');
--행 574
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'한복기능장');
--행 575
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'공간정보융합산업기사');
--행 576
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'공간정보융합기능사');
--행 577
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'제빵산업기사');
--행 578
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'화훼장식산업기사');
--행 579
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'방재기사');
--행 580
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'정밀화학기사');
--행 581
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'로봇소프트웨어개발기사');
--행 582
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'보석감정산업기사');
--행 583
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'3D프린터개발산업기사');
--행 584
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'떡제조기능사');
--행 585
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'가스텅스텐아크용접기능사');
--행 586
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'3D프린터운용기능사');
--행 587
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'식육가공기사');
--행 588
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'기술지도사(기술혁신관리)');
--행 589
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'바이오화학제품제조산업기사');
--행 590
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'고용노동부 보건직(7급)');
--행 591
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'제과산업기사');
--행 592
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'버섯산업기사');
--행 593
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'농작업안전보건기사');
--행 594
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'신발산업기사');
--행 595
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'로봇하드웨어개발기사');
--행 596
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'가구제작산업기사');
--행 597
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'보석디자인산업기사');
--행 598
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'잠수기능장');
--행 599
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'환경위해관리기사');
--행 600
INSERT INTO SKILL (SKILL_NO, SKILL_NAME) VALUES (SEQ_SKILL_NO.NEXTVAL,'로봇기구개발기사');


-- 멤버
INSERT INTO MEMBER VALUES(1, 'admin@naver.com', '$2a$10$Oa0Xd4NXm4.5/lgBkeBbBu2Y3gHAkhdOT9zgvilBHgO0dBYu1dNCm' ,'관리자', '음악', 1,
        '010-1111-0000', '서울시 강남구', 'Y', 'M', '4', 'resources/memberProfileImg/userDefaultProFile.png', 0, NULL, SYSDATE, 333300);
INSERT INTO MEMBER VALUES(SEQ_MNO.NEXTVAL, 'user01@naver.com','$2a$10$Oa0Xd4NXm4.5/lgBkeBbBu2Y3gHAkhdOT9zgvilBHgO0dBYu1dNCm' ,'홍길동', '음악', 1, 
        '010-1111-1111', '서울시 송파구', 'Y', 'M', '4', 'resources/memberProfileImg/userDefaultProFile.png', 0, NULL, SYSDATE, 333300);
INSERT INTO MEMBER VALUES(SEQ_MNO.NEXTVAL, 'user02@naver.com','$2a$10$Oa0Xd4NXm4.5/lgBkeBbBu2Y3gHAkhdOT9zgvilBHgO0dBYu1dNCm' ,'김길동', '음악', 1, 
        '010-1111-1112', '서울시 송파구', 'Y', 'M', '4', 'resources/memberProfileImg/userDefaultProFile.png', 0, NULL, SYSDATE, 333300);
INSERT INTO MEMBER VALUES(SEQ_MNO.NEXTVAL, 'user03@naver.com','$2a$10$Oa0Xd4NXm4.5/lgBkeBbBu2Y3gHAkhdOT9zgvilBHgO0dBYu1dNCm' ,'이길동', '음악', 1, 
        '010-1111-1113', '서울시 송파구', 'Y', 'M', '4', 'resources/memberProfileImg/userDefaultProFile.png', 0, NULL, SYSDATE, 333300);
INSERT INTO MEMBER VALUES(SEQ_MNO.NEXTVAL, 'user04@naver.com','$2a$10$Oa0Xd4NXm4.5/lgBkeBbBu2Y3gHAkhdOT9zgvilBHgO0dBYu1dNCm' ,'박길동', '음악', 1, 
        '010-1111-1114', '서울시 송파구', 'Y', 'M', '4', 'resources/memberProfileImg/userDefaultProFile.png', 0, NULL, SYSDATE, 333300);
INSERT INTO MEMBER VALUES(SEQ_MNO.NEXTVAL, 'user05@naver.com','$2a$10$Oa0Xd4NXm4.5/lgBkeBbBu2Y3gHAkhdOT9zgvilBHgO0dBYu1dNCm' ,'최길동', '음악', 1, 
        '010-1111-1115', '서울시 송파구', 'Y', 'M', '4', 'resources/memberProfileImg/userDefaultProFile.png', 0, NULL, SYSDATE, 333300);
INSERT INTO MEMBER VALUES(SEQ_MNO.NEXTVAL, 'user06@naver.com','$2a$10$Oa0Xd4NXm4.5/lgBkeBbBu2Y3gHAkhdOT9zgvilBHgO0dBYu1dNCm' ,'구길동', '음악', 1, 
        '010-1111-1116', '서울시 송파구', 'Y', 'M', '4', 'resources/memberProfileImg/userDefaultProFile.png', 0, NULL, SYSDATE, 333300);



INSERT INTO MEMBER(
            MEM_NO,
			MEM_EMAIL,
			MEM_PWD,
			MEM_NAME,
			MEM_CONCERN,
			PHONE,
			MEM_GEN,
            INTRO,
            ENROLL_DATE
		)
		VALUES(
            SEQ_MNO.NEXTVAL,
			'aaa@naver.com',
			'1111',
			'김개똥',
			'요리',
			'010-2222-2222',
			'M',
            NULL,
            SYSDATE
		);
--카테고리
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '음악');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '운동');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '게임');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '미술');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '댄스');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '요리');
---- 카테고리 수정안 추가본
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '교육');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '취미');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '뷰티');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '패션');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '건강');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '펫');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '부동산');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '자동차');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '금융');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, 'IT');
INSERT INTO CATEGORY VALUES(SEQ_CNO.NEXTVAL, '기타');

--게시판(보드)

INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '커뮤니티용 음악레슨합니다1', '커뮤니티용 음악 정말 즐겁게 알려드려요', 50000, 3, '2020-01-02', 'Y', 2, 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '얼마예요1', '커뮤니티용 음악 정말 즐겁게 알려드려요', 40000, 4, '2020-01-03', 'Y', 2, 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '함께해요1', '커뮤니티용 음악 정말 즐겁게 알려드려요', 40000, 5, '2020-01-04', 'Y', 2, 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '궁금해요2', '커뮤니티용 음악 정말 즐겁게 알려드려요', 40000, 3, '2020-01-05', 'Y', 2, 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '얼마예요2', '커뮤니티용 음악 정말 즐겁게 알려드려요', 40000, 4, '2020-01-06', 'Y', 2, 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '함께2', '커뮤니티용 음악 정말 즐겁게 알려드려요', 40000, 5, '2020-01-07', 'Y', 2, 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '커뮤니티용 페이징처리', '커뮤니티용 음악 정말 즐겁게 알려드려요', 40000, 3, '2020-01-08', 'Y', 2, 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '초보자도 "쉽게" <br> 볼링 알려드립니다!', '구력 15년차입니다! 
1. 친구분들과 내기에서 이기고 싶은 분 
2. 공이 옆으로 빠지지 않고 굴리고 싶은 분 
3. 동호회, 상주에서 입상 하고 싶은 분 
4. 에버리지 올리고 싶은 분 
5. 볼링 자세를 멋있게 혹은 예쁘게 치고 싶은 분 
6. 볼링을 알고싶으신 남녀노소 모두 가르쳐드립니다', 15000, 1, '2023-12-10', 'Y', '2', 201, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '홈페이지 디자인부터 제작까지 <br> 완벽하게 제작해 드립니다.', '항상 만족스러운 결과물을 드리기 위해 노력하고있습니다! 
 많은 경험과 기획부터 디자인, 개발, 퍼블리싱까지 완벽한 호흡으로
 최상의 홈페이지를 만들어 드리겠습니다.
', 400000, 1, '2023-12-11', 'Y', '3', 215, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '페이징처리용 테스트1', '페이징처리용
테스트1 내용
', 1000, 1, '2023-07-24', 'Y', '4', 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '페이징처리용 테스트2', '페이징처리용
테스트2 내용
', 1000, 1, '2023-07-24', 'Y', '4', 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '페이징처리용 테스트3', '페이징처리용
테스트3 내용
', 1000, 1, '2023-07-24', 'Y', '4', 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '페이징처리용 테스트4', '페이징처리용
테스트4 내용
', 1000, 1, '2023-07-24', 'Y', '4', 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '페이징처리용 테스트5', '페이징처리용
테스트5 내용
', 1000, 1, '2023-07-24', 'Y', '4', 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '페이징처리용 테스트6', '페이징처리용
테스트6 내용
', 1000, 1, '2023-07-24', 'Y', '4', 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '페이징처리용 테스트7', '페이징처리용
테스트7 내용
', 1000, 1, '2023-07-24', 'Y', '4', 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '노래 레슨 받고싶어요.', '음치 박치 입니다.
중간만하고싶어요 도와주세요.
레슨비 협의!
', 1000, 2, '2023-12-11', 'Y', '5', 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '롤 듀오구합니다!', '지금 에메랄드4티어입니다.
같이 다이아 갈 사람 구합니다!!
', 1000, 2, '2023-12-11', 'Y', '5', 202, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '페이징처리용 테스트1', '페이징처리용
테스트1 내용
', 1000, 2, '2023-07-24', 'Y', '5', 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '페이징처리용 테스트2', '페이징처리용
테스트2 내용
', 1000, 2, '2023-07-24', 'Y', '5', 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '페이징처리용 테스트3', '페이징처리용
테스트3 내용
', 1000, 2, '2023-07-24', 'Y', '5', 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '페이징처리용 테스트4', '페이징처리용
테스트4 내용
', 1000, 2, '2023-07-24', 'Y', '5', 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '페이징처리용 테스트5', '페이징처리용
테스트5 내용
', 1000, 2, '2023-07-24', 'Y', '5', 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '페이징처리용 테스트6', '페이징처리용
테스트6 내용
', 1000, 2, '2023-07-24', 'Y', '5', 200, 0, 0);
INSERT INTO BOARD VALUES(SEQ_BNO.NEXTVAL, '페이징처리용 테스트7', '페이징처리용
테스트7 내용
', 1000, 2, '2023-07-24', 'Y', '5', 200, 0, 0);

-- ATTACHEMT 사진
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '././resources/borderImage/2023122317051415709.jpg"', '4' , 'Y' ,1000, 0);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '././resources/borderImage/2023122317051415709.jpg"', '4' , 'Y' ,1001, 0);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '././resources/borderImage/2023122317051415709.jpg"', '4' , 'Y' ,1002, 0);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '././resources/borderImage/2023122317051415709.jpg"', '4' , 'Y' ,1003, 0);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '././resources/borderImage/2023122417073847273.jpg', '4' , 'Y' ,1004, 0);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '././resources/borderImage/2023122417073847273.jpg', '4' , 'Y' ,1005, 0);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, '22', '33', '4' , 'Y' ,1006, 0);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, 'Bowling.jpg', '././resources/borderImage/Bowling.jpg', null, 'Y', 1007, 1);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, 'It.jpg', '././resources/borderImage/It.jpg', null, 'Y', 1008, 1);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, 'test.png', '././resources/borderImage/test.png', null, 'Y', 1009, 1);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, 'test.png', '././resources/borderImage/test.png', null, 'Y', 1010, 1);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, 'test.png', '././resources/borderImage/test.png', null, 'Y', 1011, 1);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, 'test.png', '././resources/borderImage/test.png', null, 'Y', 1012, 1);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, 'test.png', '././resources/borderImage/test.png', null, 'Y', 1013, 1);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, 'test.png', '././resources/borderImage/test.png', null, 'Y', 1014, 1);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, 'test.png', '././resources/borderImage/test.png', null, 'Y', 1015, 1);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, 'mic.jpg', '././resources/borderImage/mic.jpg', null, 'Y', 1016, 1);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, 'tiers.png', '././resources/borderImage/tiers.png', null, 'Y', 1017, 1);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, 'test.png', '././resources/borderImage/test.png', null, 'Y', 1018, 1);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, 'test.png', '././resources/borderImage/test.png', null, 'Y', 1019, 1);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, 'test.png', '././resources/borderImage/test.png', null, 'Y', 1020, 1);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, 'test.png', '././resources/borderImage/test.png', null, 'Y', 1021, 1);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, 'test.png', '././resources/borderImage/test.png', null, 'Y', 1022, 1);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, 'test.png', '././resources/borderImage/test.png', null, 'Y', 1023, 1);
INSERT INTO ATTACHMENT VALUES(SEQ_ANO.NEXTVAL, 'test.png', '././resources/borderImage/test.png', null, 'Y', 1024, 1);

-- NOTICE
INSERT INTO NOTICE VALUES(SEQ_NNO.NEXTVAL, '필독', '품앗이에 대하여', '품앗이 사이트는 전문가 및 준전문가와 수요자의 매칭을 해주는 사이트입니다.', '2020-01-01', 'Y');
INSERT INTO NOTICE VALUES(SEQ_NNO.NEXTVAL, '필독', '품앗이 채용 사칭 스미싱 문자 주의', '다른 번호 외에 전화를 걸지 말아 주시고,
소비자 보호를 위해 스미싱 사이트에 접속하지 말아주시길 당부 드립니다.', '2020-01-01', 'Y');
INSERT INTO NOTICE VALUES(SEQ_NNO.NEXTVAL, '공지', '품앗이 서비스 점검안내', '사이트 및 서버 점검이 진행 될 예정입니다.
점검시간 동안 품앗이 사이트 서비스 이용이 불가능하오니 양해 부탁드립니다.', '2020-01-01', 'Y');
INSERT INTO NOTICE VALUES(SEQ_NNO.NEXTVAL, '공지', '품앗이 사기 당했을 경우', '사기 당했을 경우 신고바랍니다.', '2020-01-01', 'Y');
INSERT INTO NOTICE VALUES(SEQ_NNO.NEXTVAL, '공지', '품앗이 현피뜰 경우', '금일은 서비스 점검으로 인해 오후에 사용이 어려울 수 있습니다.
고객놈들께서는 참고하시고 이용을 하든지 말든지 진짜 귀찮게 굴지 마시고
알아서 하시길...', SYSDATE, 'Y');
INSERT INTO NOTICE VALUES(SEQ_NNO.NEXTVAL, '공지', '품앗이생활은 감옥생활', '품앗이 생활 한번 시작하면은 못빠져나간다', SYSDATE, 'Y');
-- SCHEDULE
INSERT INTO SCHEDULE VALUES(SEQ_SNO.NEXTVAL, '음악레슨신청1', '아무것도모르는 초보입니다 그래도 배워보고싶습니다1', 1000, 1, 2, 200, 'Y', SYSDATE, '서울시 강남구 역삼동');
INSERT INTO SCHEDULE VALUES(SEQ_SNO.NEXTVAL, '음악레슨신청2', '아무것도모르는 초보입니다 그래도 배워보고싶습니다2', 1000, 1, 2, 200, 'Y', SYSDATE, '서울시 강남구 역삼동');
INSERT INTO SCHEDULE VALUES(SEQ_SNO.NEXTVAL, '음악레슨신청3', '아무것도모르는 초보입니다 그래도 배워보고싶습니다3', 1000, 1, 2, 200, 'Y', SYSDATE, '서울시 강남구 역삼동');
INSERT INTO SCHEDULE VALUES(SEQ_SNO.NEXTVAL, '음악레슨신청4', '아무것도모르는 초보입니다 그래도 배워보고싶습니다4', 1000, 1, 2, 200, 'Y', SYSDATE, '서울시 강남구 역삼동');


INSERT INTO REPLY (
					REPLY_NO,
					REPLY_CONTENT,			
					MEM_NO,
					BOARD_NO,
					CREATEDATE,
					STATUS		
            		)
		VALUES(
		        SEQ_RNO.NEXTVAL,
		        '진짜 뭐하는 거임?',
		        1,
                1001,
		        SYSDATE,
		        'Y'
		        );


		SELECT  R.REPLY_NO,
				R.REPLY_CONTENT,
				M.MEM_NAME,
				R.CREATEDATE        		        
		FROM	REPLY R	
		JOIN MEMBER M ON (R.MEM_NO = M.MEM_NO) 
		WHERE R.STATUS = 'Y'
			AND BOARD_NO = 1013
		ORDER BY REPLY_NO DESC;
        

--채팅방 더미
INSERT INTO CHATROOM VALUES(1, '관리자', 'Y', 2, '홍길동', 2, '1', SYSTIMESTAMP, 1);
INSERT INTO CHATROOM VALUES(1, '관리자', 'Y', 3, '김길동', 2, '1', SYSTIMESTAMP, 1); 
INSERT INTO CHATROOM VALUES(1, '관리자', 'N', 5, '박길동', 2, '1', SYSTIMESTAMP, 1); 
INSERT INTO CHATROOM VALUES(3, '김길동', 'Y', 2, '홍길동', 2, '1', SYSTIMESTAMP, 1); --이, 박 


--메시지 더미
--INSERT INTO CHATMSG VALUES(5555, '메시지TEST', SYSTIMESTAMP, 2, 1);
--INSERT INTO CHATMSG VALUES(5556, '메시지TEST2', SYSTIMESTAMP, 2, 1);
--INSERT INTO CHATMSG VALUES(5557, '메시지TEST3', SYSTIMESTAMP, 2, 1);
--INSERT INTO CHATMSG VALUES(5558, '메시지TEST4', SYSTIMESTAMP, 2, 1);
--INSERT INTO CHATMSG VALUES(5559, '메시지TEST5', SYSTIMESTAMP, 2, 1);
--INSERT INTO CHATMSG VALUES(5560, '메시지TEST6', SYSTIMESTAMP, 1, 2);
--INSERT INTO CHATMSG VALUES(5561, '메시지TEST7', SYSTIMESTAMP, 2, 1);
--INSERT INTO CHATMSG VALUES(5562, '메시지TEST8', SYSTIMESTAMP, 1, 2);


--채팅룸x멤버 복합키 더미

--신고게시판 더미데이터
INSERT INTO REPORT(
    REPORT_NO,
    REPORT_TITLE,
    REPORT_CONTENT,
    CREATEDATE,
    MEM_NO,
    ADMIN_COMENT,
    STATUS  
)
VALUES(
    SEQ_RPNO.NEXTVAL,
    '결제 관련 문의',
    '결제 안됨',
    '2023-12-26',
    '2',
    NULL,
    'Y'
);

INSERT INTO REPORT(
    REPORT_NO,
    REPORT_TITLE,
    REPORT_CONTENT,
    CREATEDATE,
    MEM_NO,
    ADMIN_COMENT,
    STATUS  
)
VALUES(
    SEQ_RPNO.NEXTVAL,
    '오류 있어요',
    '오류있어서 결제 안됨',
    '2023-12-27',
    '2',
    NULL,
    'Y'
);

INSERT INTO REPORT(
    REPORT_NO,
    REPORT_TITLE,
    REPORT_CONTENT,
    CREATEDATE,
    MEM_NO,
    ADMIN_COMENT,
    STATUS  
)
VALUES(
    SEQ_RPNO.NEXTVAL,
    '오류 해결좀...',
    '오류 해결 해주세요',
    SYSDATE,
    '2',
    NULL,
    'N'
);


---트랜잭션
commit;

--게시판 좋아요 트리거
CREATE OR REPLACE TRIGGER likey_status_trigger
AFTER UPDATE ON LIKEY
FOR EACH ROW
WHEN (OLD.LISTATUS <> NEW.LISTATUS)
DECLARE
    likey_increment INTEGER;
BEGIN
    IF :NEW.LISTATUS = 'Y' THEN
        likey_increment := 1;
    ELSE
        likey_increment := -1;
    END IF;

    UPDATE BOARD
    SET LIKEY_COUNT = LIKEY_COUNT + likey_increment
    WHERE BOARD_NO = :NEW.BOARD_NO;
END;
/

--게시판 댓글 좋아요 트리거
CREATE OR REPLACE TRIGGER relikey_status_trigger
AFTER UPDATE ON REPLY_LIKEY
FOR EACH ROW
WHEN (OLD.RE_LISTATUS <> NEW.RE_LISTATUS)
DECLARE
    relikey_increment INTEGER;
BEGIN
    IF :NEW.RE_LISTATUS = 'Y' THEN
        relikey_increment := 1;
    ELSE
        relikey_increment := -1;
    END IF;

    UPDATE REPLY
    SET RELIKEY_COUNT = RELIKEY_COUNT + relikey_increment
    WHERE REPLY_NO = :NEW.REPLY_NO;
END;
/